<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function doi_importer_menu() {
  return array(
    'admin/islandora/scholar/doi_importer' => array(
      'title' => 'DOI Importer',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('doi_importer_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_importer().
 */
function doi_importer_islandora_importer() {
  return array(
    'doi_importer' => array(
      'title' => t('DOI Importer'),
      'class' => 'DOIImporter',
    ),
  );
}
