<?php

/**
 * @file
 * Support code to harvest records, given DOIs.
 */

const ISLANDORA_DOI_OPENURL_DEFAULT = 'https://www.crossref.org/openurl';
const ISLANDORA_DOI_OPENURL_PID_DEFAULT = 'user@example.com';
const ISLANDORA_DOI_DOIURL_DEFAULT = 'https://doi.org';

/**
 * Implements hook_menu().
 */
function islandora_doi_menu() {
  return array(
    'admin/islandora/solution_pack_config/scholar/islandora_doi' => array(
      'title' => 'DOI Configuration',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_doi_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'includes/admin.form.inc',
    ),
  );
}
