<?php
/**
 * @file
 *   The islandora_scholar moudule.
 */

define('THEME_SCHOLAR_SEARCH_ITEM', 'islandora_scholar_search_item');
define('THEME_SCHOLAR_SEARCH_ITEM_ALT', 'islandora_scholar_search_alt_item');
define('THEME_SCHOLAR_SEARCH_TABLE', 'islandora_scholar_search_results_table');

/**
 * Implements hook_theme().
 *
 */
function islandora_scholar_theme() {
  return array(
    THEME_SCHOLAR_SEARCH_ITEM => array(
      'template' => 'templates/SearchItem',
      'file' => 'includes/SolrResults.inc',
      'variables' => array('pid' => NULL, 'style' => NULL),
    ),
    THEME_SCHOLAR_SEARCH_ITEM_ALT => array(
      'template' => 'templates/SearchItem',
      'file' => 'includes/SolrResults.inc',
      'variables' => array('solr_doc' => NULL, 'style' => NULL),
    ),
    THEME_SCHOLAR_SEARCH_TABLE => array(
      'file' => 'includes/SolrResults.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_scholar_menu() {
  return array(
    'admin/islandora/scholar' => array(
      'title' => 'Scholar',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_scholar_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'islandora_scholar.admin.inc',
    ),
    'admin/islandora/scholar/base' =>  array(
      'title' => 'Basic Configuration',
      'type' => MENU_DEFAULT_LOCAL_TASK,
    ),
    'islandora/object/%islandora_object/islandora_scholar_romeo' => array(
      'title' => 'RoMEO',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_scholar_romeo_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_scholar_romeo_access',
      'access arguments' => array(2),
      'file' => 'romeo.tab.inc',
    ),
    'islandora/object/%islandora_object/islandora_scholar_upload' => array(
      'title' => 'Document',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_scholar_upload_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_scholar_upload_access',
      'access arguments' => array(2),
      'file' => 'upload.tab.inc',
    ),
  );
}

/**
 * Implements hook_islandora_solr_primary_display().
 */
function islandora_scholar_islandora_solr_primary_display() {
  return array(
    'islandora_scholar' => array(
      'name' => t('Citations'),
      'module' => 'islandora_scholar',
      'file' => 'includes/SolrResults.inc',
      'class' => "IslandoraSolrResultsCitation",
      'function' => "displayResults",
      'description' => t("Results are CSL-rendered citations. '.
        '(Requires MODS streams in objects)"),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_scholar_islandora_required_objects() {
  // Build a thumbnail datastream.
  $module_path = drupal_get_path('module', 'islandora_scholar');
  $folder_thumbnail_datastream = array(
    'dsid' => 'TN',
    'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
    'mimetype' => 'image/png',
  );

  return array(
    'islandora_scholar' => array(
      'module' => 'islandora_scholar',
      'title' => 'Islandora Scholar',
      'objects' => array(
        array(
          // Citations Collection.
          'pid' => 'ir:citationCollection',
          'label' => 'Citations',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            $folder_thumbnail_datastream,
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/XML/COLLECTION_POLICY.xml",
              'mimetype' => 'text/xml',
            ),
          ),
        ),
        array(
          // Citation Content Model.
          'pid' => 'ir:citationCModel',
          'label' => 'Citation Content Model',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/XML/ISLANDORACM.xml",
        ),
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_scholar_ir_citationCModel_islandora_view_object($object) {
  module_load_include('inc', 'islandora_scholar', 'citation.tab');
  module_load_include('inc', 'islandora_scholar', 'includes/Coins');
  $display = array(
    'citation' => array(
      '#markup' => CitationView::get_citation($object['MODS']->content),
    ),
    'viewer' => CitationView::get_viewer($object),
    'metadata' => array(
      '#type' => 'fieldset',
      '#title' => t('Metadata'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      'value' => islandora_scholar_details($object),
    ),
  );

  return array('citation.tab' => drupal_render($display));
}

/**
 * Access callback for upload tab.
 *
 * Allow if the user's allowed to add datastreams or is the object's owner.
 */
function islandora_scholar_upload_access($object) {
  global $user;
  $is_owner = property_exists($user, 'name') && ($user->name == $object->owner);
  return in_array('ir:citationCModel', $object->models) &&
    (user_access(FEDORA_ADD_DS) || $is_owner);
}

/**
 * Access callback, to determine whether or not to create the RoMEO tab.
 *
 * Checks if it's enabled, we have the relevant content model, and we have an
 * ISSN to look up.
 */
function islandora_scholar_romeo_access($object) {
  module_load_include('tab.inc', 'islandora_scholar', 'romeo');

  return variable_get('islandora_scholar_romeo_enable', FALSE) &&
    in_array('ir:citationCModel', $object->models) &&
    RomeoView::get_issn($object->pid);
}
