<?php

define('THEME_SCHOLAR_SEARCH_ITEM', 'islandora_scholar_search_item');
define('THEME_SCHOLAR_SEARCH_ITEM_ALT', 'islandora_scholar_search_alt_item');
define('THEME_SCHOLAR_SEARCH_TABLE', 'islandora_scholar_search_results_table');

function islandora_scholar_theme() {
  return array(
    THEME_SCHOLAR_SEARCH_ITEM => array(
      'template' => 'templates/SearchItem',
      'file' => 'includes/SolrResults.inc',
      'arguments' => array('pid' => NULL, 'style' => NULL)
    ),
    THEME_SCHOLAR_SEARCH_ITEM_ALT => array(
      'template' => 'templates/SearchItem',
      'file' => 'includes/SolrResults.inc',
      'arguments' => array('solr_doc' => NULL, 'style' => NULL)
    ),
    THEME_SCHOLAR_SEARCH_TABLE => array(
      'file' => 'includes/SolrResults.inc',
      'arguments' => array('element' => array()),
    ),
  );
}

/**
 * Implementation of hook_islandora_tabs().
 */
function islandora_scholar_islandora_tabs($cms, $pid, $page) {
  $tabset = array();

  foreach ($cms as $cm) {
    if ($cm->pid == 'ir:citationCollectionCModel' | $cm->pid == 'ir:authorityCollectionCModel') {
      module_load_include('inc', 'fedora_repository', 'CollectionClass');
      $cc = new CollectionClass($pid);
      $tabset += $cc->showFieldSets($page);
    }
    elseif ($cm->pid == 'ir:citationCModel') {
      module_load_include('inc', 'islandora_scholar', 'citation.tab');
      $tabset += CitationView::get_tabs($pid);
      module_load_include('inc', 'islandora_scholar', 'upload.tab');
      $tabset += UploadView::get_tabs($pid);
      module_load_include('inc', 'islandora_scholar', 'romeo.tab');
      $tabset += RomeoView::get_tabs($pid);
      module_load_include('inc', 'islandora_scholar', 'supplemental_info.tab');
    }
  }

  return $tabset;
}

/**
 * Implementation of hook_menu().
 */
function islandora_scholar_menu() {
  return array(
    'admin/settings/fedora_repository/scholar' => array(
      'title' => 'Scholar',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_scholar_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'islandora_scholar.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_islandora_object_details_display().
 */
function islandora_scholar_islandora_object_details_display() {
  return array(
    'islandora_scholar_details' => array(
      'name' => t('Scholar MODS'),
      'module' => 'islandora_scholar',
      'file' => 'includes/Coins.inc',
      'function' => 'islandora_scholar_details',
      'description' => t('Some MODS metadata extracted into a table.'),
    ),
  );
}

function islandora_scholar_islandora_solr_primary_display() {
  return array(
    'islandora_scholar' => array(
      'name' => t('Citations'),
      'module' => 'islandora_scholar',
      'file' => 'includes/SolrResults.inc',
      'class' => "IslandoraSolrResultsCitation",
      'function' => "displayResults",
      'description' => t("Results are CSL-rendered citations. '.
        '(Requires MODS streams in objects)"),
    )
  );
}
