<?php

/**
 * @file
 * Implements hooks and callbacks for this module.
 */

require_once dirname(__FILE__) . '/includes/batch.inc';

/**
 * Constants
 */
define('CITATION_EXPORTER_INDEX_SESSION', 'citation_exporter');
define('CITATION_EXPORTER_EXPORT_MENU', 'islandora/citation/export');

// @codingStandardsIgnoreStart
// XXX: These should be removed at some point in the future.
define('SESSION_CITATION_EXPORTER_INDEX', CITATION_EXPORTER_INDEX_SESSION);
define('MENU_CITATION_EXPORTER_EXPORT', CITATION_EXPORTER_EXPORT_MENU);
// @codingStandardsIgnoreEnd

/**
 * Implements hook_menu().
 */
function citation_exporter_menu() {
  $items = array();
  $items[CITATION_EXPORTER_EXPORT_MENU] = array(
    'page callback' => 'citation_exporter_export',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Export citations and redirect the user to another page.
 *
 * Menu callback.
 */
function citation_exporter_export() {
  module_load_include('inc', 'citation_exporter', 'includes/citation.export');
  CitationExporter::Export();
}
