<?php

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */
module_load_include('inc', 'citation_exporter', 'includes/batch');

/**
 * Constants
 */
define('SESSION_CITATION_EXPORTER_INDEX', 'citation_exporter');
define('MENU_CITATION_EXPORTER_EXPORT', 'islandora/citation/export');

/**
 * Implements hook_menu().
 */
function citation_exporter_menu() {
  $items = array();
  $items[MENU_CITATION_EXPORTER_EXPORT] = array(
    'page callback' => 'citation_exporter_export',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Export many citations in a particular format and redirect the user to another page.
 *
 * Menu callback.
 */
function citation_exporter_export() {
  module_load_include('inc', 'citation_exporter', 'CitationExporter');
  CitationExporter::Export();
}




