<?php

function doi_importer_menu() {
  return array(
    'admin/settings/islandora_scholar/doi_importer' => array(
      'title' => 'DOI Importer',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('doi_importer_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'doi_importer.admin.inc',
    ),
  );
}

function doi_importer_islandora_scholar_importer() {
  return array(
    'doi_importer' => array(
      'type' => 'inc',
      'module' => 'doi_importer',
      'file' => 'doi_importer',
      'title' => t('DOI Importer'),
      'class' => 'DOIImporter',
    )
  );
}
